apiVersion: apps/v1
kind: Deployment
metadata:
  name: volte-service
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: volte-service
    spec:
      containers:
        - name: volte-app
          image: volte-service:v1.0
          ports:
            - containerPort: 5060
 
